// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDV5jGHIGFgVBv-Y3D4TwNfB4-6v-4CPs',
    appId: '1:276870058509:web:a9aa10813605a220dafb44',
    messagingSenderId: '276870058509',
    projectId: 'safebump-90881',
    authDomain: 'safebump-90881.firebaseapp.com',
    storageBucket: 'safebump-90881.appspot.com',
    measurementId: 'G-S50LZGNTDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJaKLUNAOCPajZVnx5SQi3vNVXhLyfHDQ',
    appId: '1:276870058509:android:6efac6fa07cb3339dafb44',
    messagingSenderId: '276870058509',
    projectId: 'safebump-90881',
    storageBucket: 'safebump-90881.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIf8gjgqlr7RD0GepW1kmsH5_pFVl4Nu0',
    appId: '1:276870058509:ios:d3e146a22dfd05f7dafb44',
    messagingSenderId: '276870058509',
    projectId: 'safebump-90881',
    storageBucket: 'safebump-90881.appspot.com',
    iosBundleId: 'com.example.safebump',
  );
}
